### ISSUE TITLE
Using the 'git' resource outside of an application block is not working as expected

### ISSUE THREAD

**Issue by jblaine** [poise/application_git#4] opened 2016-03-01 15:19 UTC
## Description

Using the git resource's `environment` attribute to indicate a `PATH` does not work as expected. The code works as expected when exercised as a simple core Chef resource via `chef-apply` but not when used in a cookbook that has `application_git` as a dependency (for use in recipes other than this one).
## Chef Version

12.6.0
## Platform Version

Solaris 10 SPARC
## Replication Case

On our Solaris 10 SPARC machines, the following fails to find git in `/usr/rcf/bin` where it absolutely does exist and is world executable. This happens **only** when the code below is part of a cookbook that has application_git as a dependency:

```
env = {'PATH' => '/usr/rcf/bin:/usr/bin:/bin'}
git '/tmp/something' do
  repository 'https://github.com/jblaine/cookbook-sysmon.git'
  environment env
end
```
## Client Output

Note that in the compiled resource information it does show the `PATH` set as desired, so there's something low-level going on here I think.

```
/:faron # /usr/rcf/bin/git --version
git version 1.8.4.1
/:faron # chef-client -E development -o 'r701-hostdb::_update-advanced'
...
resolving cookbooks for run list: ["r701-hostdb::_update-advanced"]
Synchronizing Cookbooks:
  - application_python (4.0.0)
  - application (5.0.0)
  - build-essential (2.2.4)
  - chef_handler (1.2.0)
  - dmg (2.3.0)
  - git (4.3.4)
  - cron (1.7.2)
  - windows (1.39.0)
  - yum (3.8.2)
  - chef-vault (1.3.0)
  - yum-epel (0.6.5)
  - r701-automounting (0.2.0)
  - r701-ldap (0.1.5)
  - r701-yum (0.2.15)
  - r701-chef-vault (0.1.2)
  - r701-rcftools (0.1.2)
  - r701-openafs (1.2.0)
  - r701-apache (0.4.61)
  - r701-hostdb (2.1.8)
  - poise (2.4.0)
  - poise-languages (1.2.0)
  - poise-python (1.1.2)
  - poise-service (1.0.3)
  - application_git (1.0.0)
Compiling Cookbooks...
Converging 4 resources
Recipe: r701-hostdb::_update-advanced
  * git[/usr/tools] action sync

================================================================================
Error executing action `sync` on resource 'git[/usr/tools]'
================================================================================

Errno::ENOENT
-------------
No such file or directory - git
...
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/r701-hostdb/recipes/_update-advanced.rb:15:in `from_file'

git("/usr/tools") do
...
  environment {"PATH"=>"/usr/rcf/bin:/usr/bin:/bin"}
...
end
```
## Stacktrace

https://gist.github.com/jblaine/45a902e46d1e9047bc6f

**More importantly**, truss -e -f (like strace but for Solaris) shows the search for git as:

```
20824/1:        chdir("/usr/rcf-tools/hostdb")                  = 0
20824/1:        stat64("/usr/bin/git", 0xFFBFAC58)              Err#2 ENOENT
20824/1:        stat64("bin/git", 0xFFBFAC58)                   Err#2 ENOENT
20824/1:        stat64("/opt/chef/embedded/bin/git", 0xFFBFAC58) Err#2 ENOENT
20824/1:        stat64("/opt/chef/embedded/bin/git", 0xFFBFAC58) Err#2 ENOENT
20824/1:        stat64("/usr/local/sbin/git", 0xFFBFAC58)       Err#2 ENOENT
20824/1:        stat64("/usr/local/bin/git", 0xFFBFAC58)        Err#2 ENOENT
20824/1:        stat64("/usr/sbin/git", 0xFFBFAC58)             Err#2 ENOENT
20824/1:        stat64("/sbin/git", 0xFFBFAC58)                 Err#2 ENOENT
20824/1:        stat64("/bin/git", 0xFFBFAC58)                  Err#2 ENOENT
```

And also shows that `PATH` is **never** including `/usr/rcf/bin` and is always set to `PATH=/usr/bin:bin:/opt/chef/embedded/bin:/opt/chef/embedded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin` for every `exec`-like call.

**Comment by coderanger** [comment] 2016-03-01 19:33
Unless you are inside an `application` resource, that isn't using the resource from this cookbook. The full name of that resource is `application_git`. Chef itself (and this cookbook) doesn't handle finding the git binary (https://github.com/chef/chef/blob/master/lib/chef/provider/git.rb#L322-L324), it passes a string to `exec` in the end, which means `/bin/sh` is responsible for the lookup.

**Comment by jblaine** [comment] 2016-03-01 20:02
Noah,

Respectfully, I've just run another test and can show you a cookbook recipe that runs fine until I add 1 line to metadata.rb (`depends 'application_git'`).

Can you explain that at all?

```
# jblaine-testing-cookbook
# recipes/default.rb
env = {'PATH' => '/usr/rcf/bin:/bin:/usr/bin'}

directory '/tmp/jblaine' do
  owner 'root'
  group 'root'
  mode '0750'
end

git '/tmp/jblaine/hostdb' do
  repository 'https://gitlab.mitre.org/R701-Tools/r701-hostdb.git'
  environment env
end

execute 'rm -rf /tmp/hostdb'
```

### Success without any dependencies:

```
resolving cookbooks for run list: ["jblaine-testing-cookbook"]
Synchronizing Cookbooks:
  - jblaine-testing-cookbook (0.1.0)
Compiling Cookbooks...
Converging 3 resources
Recipe: jblaine-testing-cookbook::default
  * directory[/tmp/jblaine] action create
    - create new directory /tmp/jblaine
    - change mode from '' to '0750'
    - change owner from '' to 'root'
    - change group from '' to 'root'
  * git[/tmp/jblaine/hostdb] action sync
    - clone from https://gitlab.our.org/R701-Tools/r701-hostdb.git into /tmp/jblaine/hostdb
    - checkout ref c07814378489814f94149aa804fb5fb2347f5681 branch HEAD
  * execute[rm -rf /tmp/hostdb] action run
    - execute rm -rf /tmp/hostdb

Running handlers:
Running handlers complete
Chef Client finished, 3/3 resources updated in 13 seconds
```

### After `depends 'application_git'` added to metadata.rb:

```
resolving cookbooks for run list: ["jblaine-testing-cookbook"]
Synchronizing Cookbooks:
  - application (5.0.0)
  - build-essential (2.1.2)
  - chef_handler (1.1.6)
  - dmg (2.3.0)
  - git (4.3.4)
  - windows (1.38.4)
  - yum (3.4.0)
  - yum-epel (0.5.1)
  - poise (2.4.0)
  - poise-service (1.0.3)
  - application_git (1.0.0)
  - jblaine-testing-cookbook (0.1.0)
Compiling Cookbooks...
Converging 3 resources
Recipe: jblaine-testing-cookbook::default
  * directory[/tmp/jblaine] action create (up to date)
  * git[/tmp/jblaine/hostdb] action sync
    ================================================================================
    Error executing action `sync` on resource 'git[/tmp/jblaine/hostdb]'
    ================================================================================

    Errno::ENOENT
    -------------
    No such file or directory - git

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/jblaine-testing-cookbook/recipes/default.rb

      9: git '/tmp/jblaine/hostdb' do
     10:   repository 'https://gitlab.our.org/R701-Tools/r701-hostdb.git'
     11:   environment env
     12: end
     13:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/jblaine-testing-cookbook/recipes/default.rb:9:in `from_file'

    git("/tmp/jblaine/hostdb") do
      action [:sync]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      destination "/tmp/jblaine/hostdb"
      enable_checkout true
      revision "HEAD"
      remote "origin"
      checkout_branch "deploy"
      environment {"PATH"=>"/usr/rcf/bin:/bin:/usr/bin"}
      declared_type :git
      cookbook_name "jblaine-testing-cookbook"
      recipe_name "default"
      repository "https://gitlab.our.org/R701-Tools/r701-hostdb.git"
    end
```

**Comment by coderanger** [comment] 2016-03-01 20:09
Maybe try adding just `application` and then just `poise` to the dependencies? Might be something nested.

**Comment by jblaine** [comment] 2016-03-01 20:44
Using `application` as the only dep = failure
Using `poise` as the only dep = failure
Using `application` and `application_git` as deps = failure
Using `poise` and `application_git` as deps = failure
Removing all deps again = success

**Comment by coderanger** [comment] 2016-03-01 20:50
Okay, so something in poise is probably the issue then, since that is the minimum repro case it sounds like? For kicks maybe try putting in something unrelated as a dependency like `git` or `build-essential`? Not sure why simply having poise as a dependency would do literally anything, it doesn't autoload the code so the only thing that would run is the Halite loader stub which contains nothing but an error check in this case. I suspect there is some deeper issue we are missing.

**Comment by jblaine** [comment] 2016-03-02 00:41
Adding build-essential to deps (only dep) does not cause it to fail.

**Comment by coderanger** [comment] 2016-03-02 00:45
Okay, so that means reality isn't entirely wonky which is good. Your Poise is two releases behind, but I can't think of any reason that would cause a problem like this. Let me see if I can build a repro case locally. I'll leave this open because GitHub has no way to move issues between projects.

**Comment by coderanger** [comment] 2016-03-09 19:06
I am unable to reproduce this. I used this as the recipe:

``` ruby
package 'git'

directory '/opt/gitwat'

execute 'mv /usr/bin/git /opt/gitwat' do
  creates '/opt/gitwat/git'
end

git '/tmp/whatever' do
  repository 'https://github.com/coderanger/knife-solve.git'
  environment 'PATH' => '/opt/gitwat:/usr/bin:/bin'
end
```

It succeeds regardless of if `poise` is a dependency or not.

**Comment by grantjoy** [comment] 2016-03-14 23:13
I was getting this same issue. I was creating the directory and adding a file to it before the clone. I was able to fix this issue by removing the folder entirely and then pulling the repository to a fresh (non-existent) directory. I don't know if this is expected, but it is annoying that it doesn't work and doesn't give a meaningful error message.

**Comment by jblaine** [comment] 2016-03-22 18:50
I manually nuked the existing git repo from local disk and re-ran chef-client just now. It worked.

Running it again, it fails as shown above.

**Comment by jblaine** [comment] 2016-04-13 15:45
This is how we had to work around it, like @grantjoy . We nuke the whole repo from local disk every run and re-clone it.

```
directory node['r701-hostdb']['agent']['approot'] do
  only_if { platform_family?('solaris2') }
  recursive true
  action :delete
end

git node['r701-hostdb']['agent']['approot'] do
  depth 1
  user node['r701-hostdb']['agent']['user']
  group node['r701-hostdb']['agent']['group']
  repository node['r701-hostdb']['agent']['git_repo_url']
  revision   node['r701-hostdb']['agent']['git_revision']
  environment env
end
```

**Comment by coderanger** [comment] 2016-12-02 19:04
I'm going to close this as I can't repro and I think it sounds like a workaround was found. If this pops up again and someone has a minimal repro please let me know.

**Closed as completed by coderanger** 2016-12-02 19:04 UTC
